#pragma once

#ifdef ROBOTRACONTEUR_WINDOWS
#ifdef ROBOTRACONTEUR_COMPANION_UTIL_EXPORTS
#define ROBOTRACONTEUR_COMPANION_UTIL_API __declspec(dllexport)
#elif ROBOTRACONTEUR_COMPANION_UTIL_IMPORTS
#define ROBOTRACONTEUR_COMPANION_UTIL_API __declspec(dllimport)
#else
#define ROBOTRACONTEUR_COMPANION_UTIL_API
#endif
#else
#define ROBOTRACONTEUR_COMPANION_UTIL_API
#endif