name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v3
      with:
        path: src
    - uses: actions/checkout@v3
      with:
        path: vcpkg-robotraconteur
        repository: robotraconteur/vcpkg-robotraconteur
    - name: apt update
      run: sudo apt update
    - name: apt
      run: >
        sudo apt-get install 
        zlib1g zlib1g-dev libssl-dev libusb-1.0-0
        libusb-1.0-0-dev libdbus-1-3 libdbus-1-dev libbluetooth3 libbluetooth-dev zlib1g zlib1g-dev 
        git cmake g++ make libboost-all-dev curl libgtest-dev doxygen -qq    
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v5
      id: vcpkg
      with:
        pkgs: robotraconteur
        triplet: x64-windows-release
        token: ${{ github.token }}
        extra-args: --head --overlay-ports=${{ github.workspace }}/vcpkg-robotraconteur/ports
    - name: cmake
      run: >
        cmake -S src -B build 
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg-robotraconteur/scripts/buildsystems/vcpkg.cmake
        -DVCPKG_TARGET_TRIPLET=x64-windows-release
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_DOCUMENATION=ON
    - name: cmake build
      run: cmake --build build --config Release
    - name: archive docs
      uses: actions/upload-artifact@v2
      with:
        name: 'docs'
        path: build/docs/*